security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
cornetnexus:
  host: ${ORDS_HOST}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

